name: "Merge Upstream (Cubik65536's Fork)"
description: "Merge changes from the uppstream repo you had forked from."
author: "eXions"
branding:
  icon: git-merge
  color: black

inputs:
  upstream:
    description: 'Upstream repository owner/name. For example, exions/merge-upstream'
    required: true
  email:
    description: 'User email for git commits'
    default: 'actions@github.com'
  name:
    description: 'User name for git commits'
    default: 'Merge Upstream Action'
  upstream-branch:
    description: 'Upstream branch to merge from. For example, master'
    default: 'master'
  branch:
    description: 'Branch to merge to. For example, master'
    default: 'master'
  repository:
    description: 'Repository to merge from. For example, https://github.com/'
    default: 'https://github.com/'
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - run: |
        set -eux
        git switch -C "${{ inputs.branch }}"
        git remote add --fetch --track "${{ inputs.upstream-branch }}" upstream "${{ inputs.repository }}${{ inputs.upstream }}.git"
        git config user.email "${{ inputs.email }}"
        git config user.name "${{ inputs.name }}"
        git merge "upstream/${{ inputs.upstream-branch }}"
        git push
      shell: sh
